### ISSUE TITLE
missing track length

### ISSUE THREAD

**Issue by Sanesecurity** [arnaud-carre/sndh-player#1]
firstly, what a fab little player :)

noticed something odd:

Fileviewer is showing (3:00) as track length
SNDH Archiver viewer is showing ? as the track length, instead of  3:00

Nooisy Pillars - Sid is showing 1:17 in the archiver viewer ok

Attached screenshot:
![length](https://github.com/arnaud-carre/sndh-player/assets/15154470/4e50a396-fef3-4b51-98b0-dfec5d31f6d8)

**Comment by arnaud-carre** [comment]
should be ok in recent version
