### ISSUE TITLE
Subsong title not processed

### ISSUE THREAD

**Issue by yoyofr** [arnaud-carre/sndh-player#12]
Hi, congratulation for this great work!
I'm adding AtariSound to modizer (ios player) to improve sndh support.
In current version the subsong titles are not processed.
I've slightly adjusted the code, please find attached (SndhFile header & cpp
[SndhFile.zip](https://github.com/arnaud-carre/sndh-player/files/14071776/SndhFile.zip)
)

**Comment by arnaud-carre** [comment]
thanks for suggestion!
