### ISSUE TITLE
some sndh that crashes the library

### ISSUE THREAD

**Issue by aargirakis** [arnaud-carre/sndh-player#14]
Using SNDH-player lib in my program, when trying to play these sndh (attached) the library crashes. I've done some debugging and found out that the crash is somewhere in `m68kcpu.c` in `int m68k_execute(int num_cycles)`

[crash sndh-player.zip](https://github.com/arnaud-carre/sndh-player/files/14642146/crash.sndh-player.zip)

**Comment by arnaud-carre** [comment]
thanks for report, everything's fixed in 0.74!
