### ISSUE TITLE
Midnight_Sun.sndh wrong length

### ISSUE THREAD

**Issue by aargirakis** [arnaud-carre/sndh-player#15]
When played in 0.72 Windows binary the song is reoprted to be 1 sec. But if you look in the file TIME tag seems to be over 4 minutes.
[Midnight_Sun.zip](https://github.com/arnaud-carre/sndh-player/files/14657619/Midnight_Sun.zip)

**Comment by arnaud-carre** [comment]
seems this SNDH file is not legit. the 'TIME' marker is followed by a \0 null character, instead of a two bytes integer. This music file should be reported as non legit SNDH

**Comment by ciros88** [comment]
@arnaud-carre i agree with you but as a player i suppose it could also have a *minimum* fault tolerancy against bad rips.
Midnight_Sun.sndh flawlessly plays with MicroST beta 10
btw, i've notified it to sndh.atari.org team
