### ISSUE TITLE
Lethal Excess(ST/Falc) wrong replay

### ISSUE THREAD

**Issue by questor** [arnaud-carre/sndh-player#17]
Hi!  I'm not sure why, but the song Lethal Excess(ST/Falc) from MadMax has replay errors, the STe version of the song works correctly.

**Comment by arnaud-carre** [comment]
I just figured out this file had the exact same replay error when played using Atari sndh player like https://sndplayer.atari.org/downloads.php ( tested under Hatari emulator).
So my guess is this sndh file is corrupted

**Comment by bryc** [comment]
This bug doesn't happen in some other SNDH players though:

* AyEmul - https://bulba.untergrund.net/emulator_e.htm
* PSGplay - https://github.com/frno7/psgplay
* sc68 version 3.0.0B - https://sourceforge.net/projects/sc68/

Song in question (Web player here works fine - uses PSGplay): https://sndh.atari.org/?ID=2204

Might be worth a second look!

**Comment by arnaud-carre** [comment]
the STE version is working fine on all player. I suspect the web player you
linked is using the STE sndh file by default (and not the STF one)

**Comment by arnaud-carre** [comment]
oh sorry I didn't read well your comment, just figured out it works with
some player as you said. So there is a replay bug in my AtariAudio library,
have to investigate, thanks!

**Comment by arnaud-carre** [comment]
I didn't get what could happen. I'm pretty sure something is broken in the file, coz atari player on real atari (using HATARI emulator) are also failing.
I suspect some PC player to have patch for some specific sndh file?

I'm pretty should this sndh file sounds wrong when played on a real atari
