### ISSUE TITLE
Program emulates AY-3-891x instead of YM2149F

### ISSUE THREAD

**Issue by linuxuser2064** [arnaud-carre/sndh-player#18]
It's a minor issue, but you can clearly hear it in the envelopes (AY has 16 step envelope, YM2149 has 32 steps).

**Comment by arnaud-carre** [comment]
you're right. I plan to do the small change, just look for a nice table
measured on real hardware if available on the internet

**Comment by arnaud-carre** [comment]
fixed in v0.77
