### ISSUE TITLE
playback check please

### ISSUE THREAD

**Issue by Sanesecurity** [arnaud-carre/sndh-player#2]
This track won't fully play... stops after 2 seconds...

not sure if sndh corrupt or player issue?

Chambers_of_Shaolin_STe.sndh

Path:

sndh48lf.zip\sndh_lf\Mad_Max\Games\

**Comment by Sanesecurity** [comment]
After a bit of testing, Just to add that the above sndh file, plays ok using Jam Player, so the sndh file isn't corrupt.

**Comment by arnaud-carre** [comment]
thanks for the report! bug fix is in flight :)

**Comment by arnaud-carre** [comment]
fixed in v0.5!
