### ISSUE TITLE
(Feature Request) Add support for sc68 format

### ISSUE THREAD

**Issue by heretik3d** [arnaud-carre/sndh-player#20]
Hello, is here any chance for add support of sc68 audio format to this amazing player? It would be awesome. Thank you for considering my short suggestion and keep up the good work. :)

Btw I know about rePlayer (very similar designed github app like your SNDH Archive Player) but there's a bug saying:

"x64 version doesn't work on Intel® HD Graphics 4600 (fails in root signature or pipeline state creation, but without the hardware, I can't pinpoint the cause)"

...and I have intel, so (of course) it is not working for me.

**Comment by arnaud-carre** [comment]
SC68 already has its own replayer and library, and it also supports amiga music. This player is SNDH player only. 

About the ""x64 version doesn't work on Intel® HD Graphics 4600" problem, is it an issue with my sndh-player, or rePlayer? If it's rePlayer issue you should post a comment in rePlayer page
