### ISSUE TITLE
[Feature Request] Analyser from sndh.oxygenedemos.com

### ISSUE THREAD

**Issue by heretik3d** [arnaud-carre/sndh-player#21]
Hello dev. Can you add (optionable) that nice "Analyser" that is already included in your webpage player (sndh.oxygenedemos.com)? It is very nice visualizer, I like it. Thank you for considering my suggestion. And thank you for this amazing program. Keep up the good work.

Additional question: Are you planning to add support for more audio formats (for example: sc68) or only sndh, like name of program reflect...

**Comment by arnaud-carre** [comment]
hi! no plan to add nice gfx visualizer in sndh-player. Enjoy the web player for that! 

Also no other format support as you guessed :)
