### ISSUE TITLE
"virus" detected on exe file release v0.78

### ISSUE THREAD

**Issue by hipe-0** [arnaud-carre/sndh-player#22]
Hello there,

my w11 desktop pc lauched this error on 0.78 with Chrome. so I stay on 0.77 which works fine for now.

Awesome player, just testing now.
Thanks
Hippo

C:\Users\mouni\Desktop\2024-11-27 10_38_34-Release v0.78 · arnaud-carre_sndh-player.png
![2024-11-27 10_38_34-Release v0 78 · arnaud-carre_sndh-player](https://github.com/user-attachments/assets/299c1ee8-23e7-48ff-90f2-ff0ea96c703f)

**Comment by arnaud-carre** [comment]
probably a false positive (often happen)
