### ISSUE TITLE
sndh source question

### ISSUE THREAD

**Issue by Sanesecurity** [arnaud-carre/sndh-player#5]
AN Cool has 18 tunes here:

https://sndh.oxygenedemos.com/artist/an-cool

The windows player only shows 9 tunes.

I've checked the latest sndh archive and AN Cool's folder only has 9 tunes.

Does your web player have additional sources of sndh's that can be made available  to the windows player.

eg: 
https://sndh.oxygenedemos.com/musics/5855.sndh

**Comment by arnaud-carre** [comment]
you provide the zip archive in the windows player. The web player is able to get both the latest zip from the sndh.atari.org and the very recent .snd files. That's why web player should always show more tunes than the most recent isngle zip archive in sndh website

**Comment by Sanesecurity** [comment]
Thanks for explaining... my fault I missed the updates...
