### ISSUE TITLE
playback issue

### ISSUE THREAD

**Issue by Sanesecurity** [arnaud-carre/sndh-player#7]
Playback issue...

2023-04-16 | AN Cool | So Watt Loader | Now PC-Relative and register free. Originally stole a4,a5,a6

https://sndh.atari.org/?ID=5840

https://sndh.atari.org/ web player will play it after a little bit... 

jam player won't play it

0.70 sndh-player won't play it

**Comment by arnaud-carre** [comment]
seems this SNDH file requires a 4MiB atari machine ( some hardcoded address at $270000 inside ). Next version of my player will setup Atari to 4MiB and it's fixed. However it means this SNDH file won't play on a 1MiB real hardware, too bad
