### ISSUE TITLE
Sounding incorrect on some advanced modulating waveforms

### ISSUE THREAD

**Issue by mstempell** [arnaud-carre/sndh-player#8]
On this track of mine : "MYM PWM and cust wave jam"
Some modulation sounds incorrect compared to real hardware.
This starts at 1:39 of the track and can especially be heard at 1:55.
You can compare with a recording from real hardware here ; https://soundcloud.com/dma-sc/mym-pwm-and-custom-waveform-jam

**Comment by arnaud-carre** [comment]
I DM you in tweeter, I don't see what could be the issue here, it's mystery :)

**Comment by mstempell** [comment]
So after more investigation, the problem is actually on the SNDH embedded player, exported from maxYMiser tracker.
Then not on the emulator.
Closing the issue then (and sorry for the time you took on this...).
