### ISSUE TITLE
Export from Arkos-Tracker-2-ST as .sndh not playing correctly

### ISSUE THREAD

**Issue by NegativeCharge** [arnaud-carre/sndh-player#9]
I've used the converter from the following link to create a .SNDH file from an Arkos Tracker file: https://github.com/ggnkua/Arkos-Tracker-2-ST/blob/master/build_sndh.bat

The output plays back fine in ay_emul but I only hear loops of static in sndh-player.

I've attached an example.
[test.zip](https://github.com/arnaud-carre/sndh-player/files/12642511/test.zip)

**Comment by NegativeCharge** [comment]
I managed to fix the issue by editing the header in WinJam so perhaps the script isn’t generating compliant .sndh files?

**Comment by arnaud-carre** [comment]
yes the SNDH file header pretend the player tick rate is 2Mhz!?? instead of 50Hz :)
